import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Chakra_Petch } from "next/font/google";
import "../styles/globals.css";
import { Head } from "next/document";

const inter = Inter({ subsets: ["latin"] });
const chakra = Chakra_Petch({ subsets: ["latin"], weight: ['300'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Credit Card Validator</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
